name: Generate Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create for the release'
        required: true

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    name: Generate Release
    env:
      TAG: ${{ github.event.inputs.tag }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: bash ./build.sh

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        declare -a files

        # Add generated archives
        files+=("build/DialModeSwitcher.zip")

        gh release create -d -t "Dial Mode Switcher $TAG" "$TAG" "${files[@]}" -F build/hashes.txt